// Generated by https://quicktype.io

export interface Activity {
  data: Datum[];
  linked: any[];
  fields: Field[];
  status: Status;
}

export interface Datum {
  id: number;
  mmacId: number;
  mmacAppName: MmacAppName;
  mmacZmemId: number;
  mmacType: MmacType;
  mmacRealType: MmacType;
  mmacAppId: string;
  mmacDeviceName: MmacDeviceName;
  mmacManual: number;
  mmacStartTime: string;
  mmacEndTime: string;
  mmacTimeHour: number;
  mmacTimeMinute: number;
  mmacTimeSecond: number;
  mmacDistance: number;
  mmacDistancePoint: number;
  mmacSteps: number;
  mmacHr: number;
  mmacKilocalories: number;
  mmacCreatedTime: string;
  links: Links;
}

export interface Links {}

export enum MmacAppName {
  Garmin = 'garmin',
}

export enum MmacDeviceName {
  InstinctAPAC = 'instinctAPAC',
}

export enum MmacType {
  Running = 'RUNNING',
}

export interface Field {
  name: string;
  label: string;
  size: number;
  type: Type;
}

export enum Type {
  Datetime = 'datetime',
  Integer = 'integer',
  String = 'string',
}

export interface Status {
  page: number;
  totalRecords: number;
}
