// Generated by https://quicktype.io

export interface Event {
  categories: {[key: string]: null | string}[];
  data: {[key: string]: null | string};
  fields: {[key: string]: null | string}[];
  items: any[];
  jersey: any[];
  product: any[];
  payments: {[key: string]: null | string}[];
  prices: any[];
}
