import {EEventStatus, GetEventResponse} from '../types/event.type';

export function generateEventDetailData(
  status: EEventStatus,
): GetEventResponse {
  return {
    access: true,
    notif: null,
    data: {
      evnhId: '358',
      evnhType: '1',
      evnhName: 'Borobudur Marathon 2023 DEV',
      evnhQuotaRegistration: '100000',
      evnhFeatured: '0',
      evnhSizeChart:
        'https://borobudurmarathon.com/wp-content/uploads/2023/02/Size-Chart-Copy.jpg',
      evnhDescription:
        'Borobudur Marathon 2022 Powered by Bank Jateng kembali mengundang para runners\r\nuntuk menyebarkan semangat juang bersama masyarakat Magelang.\r\nTahun ini, bersama kita berbagi perjalanan menuju kemenangan.',
      evnhPlace: 'Candi Borobudur, Magelang, Jawa Tengah',
      evnhNote: null,
      evnhThumbnail:
        'https://borobudurmarathon.com/wp-content/uploads/2023/03/Slider11-1536x1024.jpg',
      evnhBallot: '1',
      evnhQuotaConfirmation: '100000',
      evnhTimeLimitRegistration: '2023-10-31 23:59:59',
      evnhCategory: 'Running',
      evnhLinkWeb: null,
      evnhTimeLimitConfirmation: '2023-10-31 23:59:59',
      evnhStartDate: '2023-11-12 05:00:00',
      evnhEndDate: '2023-11-12 15:00:00',
      evnhRegistrationStart: '2023-01-19 00:00:00',
      evnhRegistrationEnd: '2023-07-31 23:59:59',
      evnhStatusPublish: '1',
      evnhRegistrationStatus: '1',
      evnhTransactionExpired: '40',
      evnhStatus: '1',
    },
    categories: [
      {
        evncId: '1377',
        evncName: 'MARATHON',
        evncDesc: null,
        evncBenefit: null,
        evncVrStartDate: null,
        evncVrEndDate: null,
        evncVrReps: null,
        evncMaxDistance: null,
        evncMaxDistancePoint: null,
        evncStartDate: '2023-01-19 00:00:00',
        evncQuotaRegistration: '10',
        evncQuotaConfirmation: '100000',
        evncPrice: '1000000',
        evncHold: '1',
        evncUseQuota: '1',
      },
      {
        evncId: '1378',
        evncName: 'HALF MARATHON',
        evncDesc: '',
        evncBenefit: '',
        evncVrStartDate: null,
        evncVrEndDate: null,
        evncVrReps: null,
        evncMaxDistance: null,
        evncMaxDistancePoint: null,
        evncStartDate: '2023-01-19 00:00:00',
        evncQuotaRegistration: '1000',
        evncQuotaConfirmation: '100000',
        evncPrice: '1000000',
        evncHold: '1',
        evncUseQuota: '1',
      },
      {
        evncId: '1379',
        evncName: '10K',
        evncDesc: '',
        evncBenefit: '',
        evncVrStartDate: null,
        evncVrEndDate: null,
        evncVrReps: null,
        evncMaxDistance: null,
        evncMaxDistancePoint: null,
        evncStartDate: '2023-01-19 00:00:00',
        evncQuotaRegistration: '10',
        evncQuotaConfirmation: '100000',
        evncPrice: '1000000',
        evncHold: '1',
        evncUseQuota: '1',
      },
    ],
    fields: [
      {
        evhfId: '6215',
        evhfEvnhId: '358',
        evhfMsflId: '1',
        evhfName: 'evpaEvnhId',
        evhfType: 'Number',
        evhfLabel: 'Event',
        evhfIsAttribute: '0',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6216',
        evhfEvnhId: '358',
        evhfMsflId: '2',
        evhfName: 'evpaEvncId',
        evhfType: 'Number',
        evhfLabel: 'Ticket Category',
        evhfIsAttribute: '0',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6217',
        evhfEvnhId: '358',
        evhfMsflId: '3',
        evhfName: 'evpaName',
        evhfType: 'Text',
        evhfLabel: 'Full Name',
        evhfIsAttribute: '0',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6218',
        evhfEvnhId: '358',
        evhfMsflId: '4',
        evhfName: 'evpaEmail',
        evhfType: 'Email',
        evhfLabel: 'Email Address',
        evhfIsAttribute: '0',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6219',
        evhfEvnhId: '358',
        evhfMsflId: '5',
        evhfName: 'evpaPhone',
        evhfType: 'Phone',
        evhfLabel: 'Phone Number',
        evhfIsAttribute: '0',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6220',
        evhfEvnhId: '358',
        evhfMsflId: '6',
        evhfName: 'evpaGender',
        evhfType: 'Option',
        evhfLabel: 'Gender',
        evhfIsAttribute: '0',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: '/api/v1/resources/master_gender',
      },
      {
        evhfId: '6221',
        evhfEvnhId: '358',
        evhfMsflId: '7',
        evhfName: 'evpaBirthPlace',
        evhfType: 'Text',
        evhfLabel: 'Place of Birth',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6222',
        evhfEvnhId: '358',
        evhfMsflId: '8',
        evhfName: 'evpaBirthDate',
        evhfType: 'Date',
        evhfLabel: 'Date of Birth',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6223',
        evhfEvnhId: '358',
        evhfMsflId: '9',
        evhfName: 'evpaAddress',
        evhfType: 'Text',
        evhfLabel: 'Address',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6224',
        evhfEvnhId: '358',
        evhfMsflId: '10',
        evhfName: 'evpaCity',
        evhfType: 'Text',
        evhfLabel: 'City',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6225',
        evhfEvnhId: '358',
        evhfMsflId: '121',
        evhfName: 'evpaProvinsi',
        evhfType: 'Text',
        evhfLabel: 'Province',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6226',
        evhfEvnhId: '358',
        evhfMsflId: '11',
        evhfName: 'evpaCountry',
        evhfType: 'Option',
        evhfLabel: 'Country',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6227',
        evhfEvnhId: '358',
        evhfMsflId: '12',
        evhfName: 'evpaNationality',
        evhfType: 'Option',
        evhfLabel: 'Nationality',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6228',
        evhfEvnhId: '358',
        evhfMsflId: '15',
        evhfName: 'evpaEmergencyContactName',
        evhfType: 'Text',
        evhfLabel: 'Name of Emergency Contact',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6229',
        evhfEvnhId: '358',
        evhfMsflId: '16',
        evhfName: 'evpaEmergencyContactNumber',
        evhfType: 'Phone',
        evhfLabel: 'Phone Number of Emergency Contact',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6230',
        evhfEvnhId: '358',
        evhfMsflId: '26',
        evhfName: 'evpaIDNumberType',
        evhfType: 'Option',
        evhfLabel: 'ID Number Type',
        evhfIsAttribute: '0',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData:
          '[{"id":1,"label":"KTP"},{"id":2,"label":"PASSPORT"},{"id":3,"label":"SIM"},{"id":4,"label":"Kartu Pelajar / Student Card"}]',
      },
      {
        evhfId: '6231',
        evhfEvnhId: '358',
        evhfMsflId: '27',
        evhfName: 'evpaIDNumber',
        evhfType: 'Text',
        evhfLabel: 'ID Number',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6232',
        evhfEvnhId: '358',
        evhfMsflId: '29',
        evhfName: 'evpaCommunity',
        evhfType: 'Text',
        evhfLabel: 'Community',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: null,
      },
      {
        evhfId: '6233',
        evhfEvnhId: '358',
        evhfMsflId: '14',
        evhfName: 'evpaBloodType',
        evhfType: 'Option',
        evhfLabel: 'Blood Type',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData:
          '[{"id":0,"label":"O"},{"id":1,"label":"O+"},{"id":2,"label":"O-"},{"id":3,"label":"A"},{"id":4,"label":"A+"},{"id":5,"label":"A-"},{"id":6,"label":"B"},{"id":7,"label":"B+"},{"id":8,"label":"B-"},{"id":9,"label":"AB"},{"id":10,"label":"AB+"},{"id":11,"label":"AB-"}]',
      },
      {
        evhfId: '6234',
        evhfEvnhId: '358',
        evhfMsflId: '22',
        evhfName: 'evpaMedicalTreatment',
        evhfType: 'Option',
        evhfLabel:
          'Have you ever received medical treatment during the last 1 month?',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: '[{"id":1, "label":"Yes"},{"id":2, "label":"No"}]',
      },
      {
        evhfId: '6235',
        evhfEvnhId: '358',
        evhfMsflId: '356',
        evhfName: 'evpaMentionTreatment',
        evhfType: 'Text',
        evhfLabel: 'If so, what medical treatment did you receive?',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: null,
      },
      {
        evhfId: '6236',
        evhfEvnhId: '358',
        evhfMsflId: '357',
        evhfName: 'evpaLongTreatment',
        evhfType: 'Text',
        evhfLabel: 'How long did the treatment take?',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: null,
      },
      {
        evhfId: '6237',
        evhfEvnhId: '358',
        evhfMsflId: '24',
        evhfName: 'evpaBIBName',
        evhfType: 'Text',
        evhfLabel: 'Name on the BIB',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6238',
        evhfEvnhId: '358',
        evhfMsflId: '31',
        evhfName: 'evpaWave',
        evhfType: 'Time',
        evhfLabel: 'Target Waktu',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData: null,
      },
      {
        evhfId: '6239',
        evhfEvnhId: '358',
        evhfMsflId: '42',
        evhfName: 'evpaSourceURL',
        evhfType: 'Hidden',
        evhfLabel: 'Source URL',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: null,
      },
      {
        evhfId: '6240',
        evhfEvnhId: '358',
        evhfMsflId: '240',
        evhfName: 'evpaFRrace',
        evhfType: 'Text',
        evhfLabel:
          'What is the race name when you had the fastest official finish time within past 2 years?',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: null,
      },
      {
        evhfId: '6241',
        evhfEvnhId: '358',
        evhfMsflId: '237',
        evhfName: 'evpaFRtime',
        evhfType: 'Option',
        evhfLabel:
          'What is your official finish time of the race mentioned above?',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: null,
      },
      {
        evhfId: '6242',
        evhfEvnhId: '358',
        evhfMsflId: '238',
        evhfName: 'evpaFRcertificate',
        evhfType: 'File',
        evhfLabel:
          'Upload your official certificate that includes your finish time. (File PDF/JPG, max. 5 MB)',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: null,
      },
      {
        evhfId: '6243',
        evhfEvnhId: '358',
        evhfMsflId: '239',
        evhfName: 'evpaFRlink',
        evhfType: 'Text',
        evhfLabel:
          'Attach the URL link to your race result certicifate from the official website of the race.',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '0',
        evhfExternalData: null,
      },
      {
        evhfId: '6244',
        evhfEvnhId: '358',
        evhfMsflId: '13',
        evhfName: 'evpaJersey',
        evhfType: 'Option',
        evhfLabel: 'Size Jersey',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData:
          '[{"id":1,"label":"XS"},{"id":2,"label":"S"},{"id":3,"label":"M"},{"id":4,"label":"L"},{"id":5,"label":"XL"},{"id":6,"label":"XXL"},{"id":10,"label":"XXXL"}]',
      },
      {
        evhfId: '6245',
        evhfEvnhId: '358',
        evhfMsflId: '308',
        evhfName: 'evpaCovidVaksin',
        evhfType: 'Option',
        evhfLabel: 'Please indicate your Covid-19 Vaccination Status',
        evhfIsAttribute: '1',
        evhfConditions: null,
        evhfIsRequired: '1',
        evhfExternalData:
          '[{"id":1, "label":"1st dose"},{"id":2, "label":"2nd dose"},{"id":3, "label":"3rd dose"},{"id":4, "label":"Unable to receive any vaccination due to medical reason"}]',
      },
    ],
    banner: [
      {
        eimgId: '1',
        eimgName: 'banner 1',
        eimgDescription: 'test',
        eimgUrlImage:
          'https://borobudurmarathon.com/wp-content/uploads/2022/05/STRONGER-TO-VICTORYREV-1536x1024.jpg',
      },
      {
        eimgId: '2',
        eimgName: 'banner 2',
        eimgDescription: 'test',
        eimgUrlImage:
          'https://borobudurmarathon.com/wp-content/uploads/2022/05/MENUMBUHKAN-BIBIT-SEMANGATREV-1536x1024.jpg',
      },
      {
        eimgId: '3',
        eimgName: 'banner 3',
        eimgDescription: 'test',
        eimgUrlImage:
          'https://borobudurmarathon.com/wp-content/uploads/2022/05/MENGINSPIRASI-DAN-TERINSPIRASIREV-1536x1024.jpg',
      },
    ],
    payments: [
      {
        evptId: '1153',
        evptEvnhId: '358',
        evptMsptId: '10',
        evptMsptName: 'virtual_account_jateng',
        evptLabel: 'VA Bank Jateng',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1154',
        evptEvnhId: '358',
        evptMsptId: '22',
        evptMsptName: 'snap_cc_bri',
        evptLabel: 'CC BRI',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1155',
        evptEvnhId: '358',
        evptMsptId: '24',
        evptMsptName: 'save_duit',
        evptLabel: 'Saveduit Bank Jateng',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1156',
        evptEvnhId: '358',
        evptMsptId: '6',
        evptMsptName: 'snap_cc',
        evptLabel: 'CC BNI',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1157',
        evptEvnhId: '358',
        evptMsptId: '23',
        evptMsptName: 'snap_alfamart',
        evptLabel: 'Alfamart',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1158',
        evptEvnhId: '358',
        evptMsptId: '15',
        evptMsptName: 'snap_gopay',
        evptLabel: 'GOPAY',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1159',
        evptEvnhId: '358',
        evptMsptId: '28',
        evptMsptName: 'snap_va_bri',
        evptLabel: 'VA BRI',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1160',
        evptEvnhId: '358',
        evptMsptId: '12',
        evptMsptName: 'virtual_account_bni',
        evptLabel: 'VA BNI',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1161',
        evptEvnhId: '358',
        evptMsptId: '7',
        evptMsptName: 'snap_va',
        evptLabel: 'VA Permata',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
      {
        evptId: '1162',
        evptEvnhId: '358',
        evptMsptId: '9',
        evptMsptName: 'free_slot',
        evptLabel: 'Kode Promo / Kode Voucher',
        evptIsEnabled: '1',
        evptAmountFee: '0',
        evptIsPublic: '1',
      },
    ],
    payments_special: [
      {
        evptId: '1155',
        evptEvnhId: '358',
        evptMsptId: '24',
        evptMsptName: 'save_duit',
        evptLabel: 'Saveduit Bank Jateng',
        evptIsEnabled: 1,
        evptAmountFee: '0',
        evptIsPublic: 1,
      },
    ],
    prices: [],
    quota: {
      registration: false,
      payments: [
        {
          trnsEventId: '358',
          trnsPaymentType: '10',
          trnsConfirmed: '2',
          trnsPending: '0',
          trnsTotal: '2',
        },
        {
          trnsEventId: '358',
          trnsPaymentType: '24',
          trnsConfirmed: '1',
          trnsPending: '0',
          trnsTotal: '1',
        },
      ],
    },
  };
}
